# Generated by Django 2.2.5 on 2021-08-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/users/'),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='currency',
            field=models.CharField(blank=True, choices=[('rp', 'USD'), ('rp', 'KRW'), ('rp', 'RP')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('kr', 'Korean'), ('id', 'Bahasa')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='superhost',
            field=models.BooleanField(default=False),
        ),
    ]
